<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height">
    <link href="style.css" rel="stylesheet" type="text/css"/>
    <title>Pirmas namų darbas - paveikslėlio įkėlimas</title>
</head>
<body>
<div id="wrap">
    {$image}
    <div class="messages">
        <span class="message {$message_type}">
            {$message}
        </span>
    </div>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            Pasirinkite failą: <input type="file" name="image" accept="{$accept}"/><br/>
            <input type="submit" value="Įkelti"/>
        </form>
    </div>
    <div class="info">
        <ul>
            <li>Maksimalus paveikslėlio dydis: {$max_size}</li>
            <li>Palaikomi formatai: {$file_types}</li>
        </ul>
    </div>
    <footer>Copyright 2013 Andrius Petrauskis</footer>
</div>

</body>
</html>
